# Generated by Django 6.0.5 on 2026-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=300, verbose_name='Bot Token')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Chat ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
